// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCCK-JYkMd3BlBH4BpthF6Kc3IAAsVBV4',
    appId: '1:237901334227:web:25510451013dd776547626',
    messagingSenderId: '237901334227',
    projectId: 'luminasync-e9f56',
    authDomain: 'luminasync-e9f56.firebaseapp.com',
    storageBucket: 'luminasync-e9f56.appspot.com',
    measurementId: 'G-SXBXS1XRDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHX34JiPY0j4fzKzFCxDOVFOIqygmoGQ8',
    appId: '1:237901334227:android:781d62fdb24001d1547626',
    messagingSenderId: '237901334227',
    projectId: 'luminasync-e9f56',
    storageBucket: 'luminasync-e9f56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAogzEtKu3ZB2JYMDbRNE5Z67acxaBne7g',
    appId: '1:237901334227:ios:3fb0ed66dddf75f0547626',
    messagingSenderId: '237901334227',
    projectId: 'luminasync-e9f56',
    storageBucket: 'luminasync-e9f56.appspot.com',
    androidClientId: '237901334227-po37kpc5u6g43b3rigck47ce24pd23sn.apps.googleusercontent.com',
    iosClientId: '237901334227-45fobdl8votum4bmcdm0k6cpjkufs6nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.luminasyncflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAogzEtKu3ZB2JYMDbRNE5Z67acxaBne7g',
    appId: '1:237901334227:ios:790aeef6c6dc741e547626',
    messagingSenderId: '237901334227',
    projectId: 'luminasync-e9f56',
    storageBucket: 'luminasync-e9f56.appspot.com',
    androidClientId: '237901334227-po37kpc5u6g43b3rigck47ce24pd23sn.apps.googleusercontent.com',
    iosClientId: '237901334227-lj5aspb3oca3ocjn39399al6vffuslq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.luminasyncflutter.RunnerTests',
  );
}
